// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Picole.WebApi.Models;
using System;

namespace Picole.WebApi.Migrations
{
    [DbContext(typeof(PicoleDbContext))]
    [Migration("20180524173240_AddExtrasTable")]
    partial class AddExtrasTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Picole.WebApi.Models.Extra", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Oid");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Fermentable", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("Vendor");

                    b.HasKey("Oid");

                    b.ToTable("Fermentables");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Hops", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("Vendor");

                    b.HasKey("Oid");

                    b.ToTable("Hops");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Unit", b =>
                {
                    b.Property<Guid>("Oid");

                    b.Property<string>("Name");

                    b.HasKey("Oid");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Yeast", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("ProductNumber");

                    b.Property<string>("Vendor");

                    b.HasKey("Oid");

                    b.ToTable("Yeasts");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Unit", b =>
                {
                    b.HasOne("Picole.WebApi.Models.Extra")
                        .WithOne("Unit")
                        .HasForeignKey("Picole.WebApi.Models.Unit", "Oid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
