// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Picole.WebApi.Models;
using System;

namespace Picole.WebApi.Migrations
{
    [DbContext(typeof(PicoleDbContext))]
    [Migration("20180524173042_AddHopsTable")]
    partial class AddHopsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Picole.WebApi.Models.Fermentable", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("Vendor");

                    b.HasKey("Oid");

                    b.ToTable("Fermentables");
                });

            modelBuilder.Entity("Picole.WebApi.Models.Hops", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<string>("Vendor");

                    b.HasKey("Oid");

                    b.ToTable("Hops");
                });
#pragma warning restore 612, 618
        }
    }
}
